/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import controller.ProjectController;
import java.sql.Connection;
import java.util.Date;
import java.util.List;
import model.Project;
import util.ConnectionFactory;

public class Main {
   

    public static void main(String[] args) {
     // 
      // ProjectController projectController = new ProjectController();
       
      // Date data = new Date();
       
      // Project project = new Project();
      // project.setName("Projeto teste");
      // project.setDescription("description");
      // project.setUpdatedAt(data);
      // project.setCreatedAt(data);
      // projectController.save(project);
         
       
 ProjectController projectController = new ProjectController(); 
 
 Project project = new Project();
 project.setId(12);
 project.setName("Novo nome do Projeto");
 project.setDescription("description");
 projectController.update(project);
 
List<Project> projects = projectController.getAll();
System.out.println ("Total de Projetos = " + projects.size()); 
projectController.removeById(12);
   }

    }
